# Generated by Django 3.1.6 on 2021-02-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('time_in_round_one', models.IntegerField(blank=True, null=True)),
                ('time_in_round_two', models.IntegerField(blank=True, null=True)),
                ('time_in_round_three', models.IntegerField(blank=True, null=True)),
                ('winners', models.BooleanField(default=True)),
            ],
        ),
    ]
