# Generated by Django 3.1.6 on 2021-02-18 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='details',
            name='team_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.teamname'),
        ),
    ]
