# Generated by Django 3.1.6 on 2021-02-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_auto_20210218_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='winners',
        ),
        migrations.AddField(
            model_name='details',
            name='winners_in_round_one',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='details',
            name='winners_in_round_three',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='details',
            name='winners_in_round_two',
            field=models.BooleanField(default=True),
        ),
    ]
