# Generated by Django 3.1.6 on 2021-02-18 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_auto_20210218_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='time_in_round_three',
            new_name='avg_time_in_round_three',
        ),
    ]
